# Generated by Django 4.2.7 on 2024-01-28 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listitem',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listitem',
            name='due_date',
            field=models.DateField(null=True),
        ),
    ]
